### ISSUE TITLE
IOS pixelate when wrapped by any RTL Layout

### ISSUE THREAD

**Issue by bellalMohamed** [nativescript-rtl/ui#10]
IOS pixelate when wrapped by any RTL Layout

RTL disabled
<img width="69" alt="Screen Shot 2020-06-18 at 6 32 21 AM" src="https://user-images.githubusercontent.com/18222754/84978539-7868cc00-b12d-11ea-85f1-14661930c11b.png">

RTL enabled
<img width="78" alt="Screen Shot 2020-06-18 at 6 32 16 AM" src="https://user-images.githubusercontent.com/18222754/84978571-8dddf600-b12d-11ea-81af-fd3d5f08466d.png">

**Comment by xlmnxp** [comment]
`📦  @nativescript-rtl/ui@0.1.5` on npm
thank you for fix

**Comment by arturikoX** [comment]
Hi, this is still happening on version 0.1.6 with ns 6.5, any help please ?

thanks!

**Comment by howieluo** [comment]
I encounter the issue on 0.1.6 too.

**Comment by howieluo** [comment]
@xlmnxp Hi Salem, 
Our project depends on your plugin to implement RTL. Do you have any schedule to fix the issue? 
Thank you in advance.

**Comment by xlmnxp** [comment]
> @xlmnxp Hi Salem,
> Our project depends on your plugin to implement RTL. Do you have any schedule to fix the issue?
> Thank you in advance.

Is this happening for sub components only or all cases

**Comment by howieluo** [comment]
For my project, texts and images in GridLayout will be pixelated on iOS platform.

**Comment by howieluo** [comment]
I will try your fix. Thanks a lot.

**Comment by howieluo** [comment]
> I will try your fix. Thanks a lot.
Great. It works well.

**Comment by howieluo** [comment]
@xlmnxp 
Now I just can install 0.1.8 using npm.
Could you please upgrade the latest npm version of nativescript-rtl/ui from 0.1.8 to 0.1.9 ?

**Comment by xlmnxp** [comment]
> @xlmnxp
> Now I just can install 0.1.8 using npm.
> Could you please upgrade the latest npm version of nativescript-rtl/ui from 0.1.8 to 0.1.9 ?

version 0.2.0 release days ago
