### ISSUE TITLE
[Angular 10] It is not working with angular 10 version of the Nativescript

### ISSUE THREAD

**Issue by boris01** [nativescript-rtl/ui#15]
Hello,
I tried to upgrade my project to the Angular 10.
But even that I did add this library to the ngcc it still give me an errors:
ERROR in ../node_modules/@nativescript-rtl/ui/absolute-layout/absolute-layout.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/properties/properties' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui\absolute-layout'
 @ ../node_modules/@nativescript-rtl/ui/absolute-layout/absolute-layout.common.js 4:19-76
 @ ../node_modules/@nativescript-rtl/ui/absolute-layout/absolute-layout.android.js
 @ ../node_modules/@nativescript-rtl/ui/main.js
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

ERROR in ../node_modules/@nativescript-rtl/ui/dock-layout/dock-layout.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/properties/properties' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui\dock-layout'
 @ ../node_modules/@nativescript-rtl/ui/dock-layout/dock-layout.common.js 4:19-76
 @ ../node_modules/@nativescript-rtl/ui/dock-layout/dock-layout.ios.js
 @ ../node_modules/@nativescript-rtl/ui/main.js
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

ERROR in ../node_modules/@nativescript-rtl/ui/grid-layout/grid-layout.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/properties/properties' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui\grid-layout'
 @ ../node_modules/@nativescript-rtl/ui/grid-layout/grid-layout.common.js 4:19-76
 @ ../node_modules/@nativescript-rtl/ui/grid-layout/grid-layout.ios.js
 @ ../node_modules/@nativescript-rtl/ui/main.js
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

ERROR in ../node_modules/@nativescript-rtl/ui/stack-layout/stack-layout.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/properties/properties' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui\stack-layout'
 @ ../node_modules/@nativescript-rtl/ui/stack-layout/stack-layout.common.js 4:19-76
 @ ../node_modules/@nativescript-rtl/ui/stack-layout/stack-layout.ios.js
 @ ../node_modules/@nativescript-rtl/ui/main.js
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

ERROR in ../node_modules/@nativescript-rtl/ui/wrap-layout/wrap-layout.common.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/properties/properties' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui\wrap-layout'
 @ ../node_modules/@nativescript-rtl/ui/wrap-layout/wrap-layout.common.js 4:19-76
 @ ../node_modules/@nativescript-rtl/ui/wrap-layout/wrap-layout.ios.js
 @ ../node_modules/@nativescript-rtl/ui/main.js
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

ERROR in ../node_modules/@nativescript-rtl/ui/main.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/page/page' in 'H:\Nipendo\mBdox\node_modules\@nativescript-rtl\ui'
 @ ../node_modules/@nativescript-rtl/ui/main.js 3:13-53
 @ ./app/app.module.tns.ts
 @ ./main.tns.ts

**Comment by xlmnxp** [comment]
That happened because the implement of new NativeScript packages
I will fix it but that will not make older versions of NativeScript

**Comment by boris01** [comment]
Hello,
Any progress with this issue?

**Comment by xlmnxp** [comment]
I will do it now

**Comment by xlmnxp** [comment]
I'm working on support RTL officially on NativeScript

**Comment by xlmnxp** [comment]
version 0.1.7 should fix the issue
If the issue still there tell me to reopen it

**Comment by boris01** [comment]
Thanks,
I'll try it
