### ISSUE TITLE
not working in Nativescript angular 

### ISSUE THREAD

**Issue by Rmadhuprasanth** [nativescript-rtl/ui#17]
` <GridLayout rows="auto" columns="auto,auto" width="100%"   left="30" top="60"  >
                <RGridLayout isRtl="true" row="0" col="0" rows="auto" columns="auto,auto,auto" width="80%" >
                    <Image row="0" verticalAlignment="center" horizontalAlignment="center" col="0"
                        src="" class="enddot"></Image>
                <Label row="0" col="1"  verticalAlignment="center" class="line" ></Label>
                    <Gif src="~/assets/gifs/gif-for-measurment-60x60.png" row="0" col="2" class="gifimg"
                        horizontalAlignment="center" verticalAlignment="center"></Gif>
                </RGridLayout> 
                <Button row="0" col="1" text=""  horizontalAlignment="left" class="btntxt"></Button>
            </GridLayout> `

System.err: TypeError: Could not load view for: RGridLayout.TypeError: ui_1.Property is not a constructor
System.err: 
System.err: StackTrace:
System.err: getViewClass(file: node_modules\@nativescript\angular\element-registry.js:84:0)
System.err:     at push.../node_modules/@nativescript/angular/view-util.js.ViewUtil.createView(file: node_modules\@nativescript\angular\view-util.js:214:0)
System.err:     at push.../node_modules/@nativescript/angular/renderer.js.NativeScriptRenderer.createElement(file: node_modules\@nativescript\angular\renderer.js:138:0)
System.err:     at push.../node_modules/@nativescript/angular/renderer.js.EmulatedRenderer.createElement(file: node_modules\@nativescript\angular\renderer.js:415:0)
System.err:     at push.../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.createElement(file: node_modules\@angular\core\fesm5\core.js:30377:0)
System.err:     at createElement(file: node_modules\@angular\core\fesm5\core.js:28409:0)
System.err:     at createViewNodes(file: node_modules\@angular\core\fesm5\core.js:29348:0)
System.err:     at createEmbeddedView(file: node_modules\@angular\core\fesm5\core.js:29295:0)
System.err:     at callWithDebugContext(file: node_modules\@angular\core\fesm5\core.js:30309:0)
System.err:     at debugCreateEmbeddedView(file: node_modules\@angular\core\fesm5\core.js:29833:0)
System.err:     at push.../node_modules/@angular/core/fesm5/core.js.TemplateRef_.createEmbeddedView(file: node_modules\@angular\core\fesm5\core.js:20742:0)
System.err:     at push.../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createEmbeddedView(file: node_modules\@angular\core\fesm5\core.js:20608:0)
System.err:     at push.../node_modules/@angular/common/fesm5/common.js.NgIf._updateView(file: node_modules\@angular\common\fesm5\common.js:4018:0)
System.err:     at set(file: node_modules\@angular\common\fesm5\common.js:3980:0)
System.err:     at updateProp(file: node_modules\@angular\core\fesm5\core.js:21303:0)
System.err:     at checkAndUpdateDirectiveInline(file: node_modules\@angular\core\fesm5\core.js:21054:0)
System.err:     at checkAndUpdateNodeInline(file: node_modules\@angular\core\fesm5\core.js:29495:0)
System.err:     at checkAndUpdateNode(file: node_modules\@angular\core\fesm5\core.js:29457:0)
System.err:     at debugCheckAndUpdateNode(file: node_modules\@angular\core\fesm5\core.js:30091:0)
System.err:     at debugCheckDirectivesFn(file: node_modules\@angular\core\fesm5\core.js:30051:0)
System.err:     at eval(:335:5)
System.err:     at debugUpdateDirectives(file: node_modules\@angular\core\fesm5\core.js:30043:0)
System.err:     at checkAndUpdateView(file: node_modules\@angular\core\fesm5\core.js:29439:0)
System.err:     at callViewAction(file: node_modules\@angular\core\fesm5\core.js:29680:0)
System.err:     at execEmbeddedViewsAction(file: node_modules\@angular\core\fesm5\core.js:29643:0)
System.err:     at checkAndUpdateView(file: node_modules\@angular\core\fesm5\core.js:29440:0)
System.err:     at callViewAction(file: node_modules\@angular\core\fesm5\core.js:29680:0)
System.err:     at execEmbeddedViewsAction(file: node_modules\@angular\core\fesm5\core.js:29643:0)
System.err:     at checkAndUpdateView(file: node_modules\@angular\core\fesm5\core.js:29440:0)
System.err:     at callViewAction(file: node_modules\@angular\core\fesm5\core.js:29680:0)
System.err:     at execEmbeddedViewsAction(file: node_modules\@angular\core\fesm5\core.js:29643:0)
System.err:     at checkAndUpdateView(file: node_modules\@angular\core\fesm5\core.js:29440:0)
System.err:     at callWithDebugContext(file: node_modules\@angular\core\fesm5\core.js:30309:0)
System.err:     at debugCheckAndUpdateView(file: node_modules\@angular\core\fesm5\core.js:30011:0)
System.err:     at push.../node_modules/@angular/core/fesm5/core.js.ViewRef_.detectChanges(file: node_modules\@angular\core\fesm5\core.js:20686:0)System.err:     at push.../node_modules/nativescript-pager/angular/pager-items-comp.js.TemplatedItemsComponent.detectChangesOnChild(file: node_modules\nativescript-pager\angular\pager-items-comp.js:200:0)
System.err:     at push.../node_modules/nativescript-pager/angular/pager-items-comp.js.TemplatedItemsComponent.onItemLoading(file: node_modules\nativescript-pager\angular\pager-items-comp.js:146:0)
System.err:     at push.../node_modules/@nativescript/core/data/observable/observable.js.Observable.notify(file: node_modules\@nativescript\core\data\observable\observable.js:121:0)
System.err:     at PagerRecyclerAdapterImpl.onBindViewHolder(file: node_modules\nativescript-pager\pager.android.js:782:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.androidx.recyclerview.widget.RecyclerView_Adapter_vendor_157995_32_PagerRecyclerAdapterImpl.onBindViewHolder(RecyclerView_Adapter_vendor_157995_32_PagerRecyclerAdapterImpl.java:51)
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
System.err:     at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChild(ViewGroup.java:6240)
System.err:     at androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:498)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:825)
System.err:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:511)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:956)
System.err:     at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:754)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:847)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:956)
System.err:     at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:754)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:847)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.VerticalScrollView.onMeasure(VerticalScrollView.java:147)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
System.err:     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
System.err:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:749)
System.err:     at android.view.View.measure(View.java:20084)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2642)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1579)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1848)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1464)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6984)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:709)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:644)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
System.err:     at android.os.Handler.handleCallback(Handler.java:836)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     at android.os.Looper.loop(Looper.java:203)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6251)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by boris01** [comment]
What version do you use?
Can you post your package.json

**Comment by Rmadhuprasanth** [comment]
`{
  "nativescript": {
    "id": "org.nativescript.tailor",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript-rtl/ui": "^0.1.7",
    "@nativescript/theme": "~2.3.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@types/jest": "^26.0.0",
    "guid-typescript": "^1.0.9",
    "jest": "^26.0.1",
    "nativescript-angular": "~8.21.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-dna-deviceinfo": "^2.4.3",
    "nativescript-drop-down": "^5.0.5",
    "nativescript-geocoding": "^2.0.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.6",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-google-places-autocomplete": "^1.0.3",
    "nativescript-here": "0.0.1",
    "nativescript-http-formdata": "^2.1.0",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-mapbox": "^5.0.1",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-pager": "^12.0.0-alpha.9",
    "nativescript-permissions": "^1.3.9",
    "nativescript-radial-gradient": "^0.8.0",
    "nativescript-range-seek-bar": "^1.0.3",
    "nativescript-sms-inbox": "^2.1.0",
    "nativescript-sms-receiver": "^1.0.1",
    "nativescript-star-ratings": "^1.0.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-listview": "^8.2.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "ng-otp-input": "^1.7.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "tns-ng-gif": "^1.3.1",
    "ts-jest": "^26.1.0",
    "uuid": "^8.3.0",
    "uuid-generator-ts": "^1.0.4",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^9.0.0",
    "@ngtools/webpack": "~8.2.0",
    "@schematics/angular": "^9.1.9",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "^4.7.1",
    "tns-platform-declarations": "^6.5.12",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "20a65d338ae8f8911087ab6615b89363f864b07b",
  "readme": "NativeScript Application"
}
`

**Comment by boris01** [comment]
You are using the version for the Nativescript 7.
Upgrade your project to NS7 or use older version of this plugin (0.1.4)

**Comment by Rmadhuprasanth** [comment]
ok thanks 
will try it now n let u know

**Comment by Rmadhuprasanth** [comment]
damn man its working like hell cheers!!!!
any thanks for quick response!!
