### ISSUE TITLE
Not working in Nativescript Angular IOS 

### ISSUE THREAD

**Issue by Rmadhuprasanth** [nativescript-rtl/ui#18]
using "@nativescript-rtl/ui": "^0.1.4",
  "tns-ios": {
      "version": "6.5.4"
    }

`2021-03-05 22:53:42.536075+0530 mzyoontailor[12214:886448] CONSOLE ERROR [native code]: ERROR TypeError: Could not load view for: RGridLayout.TypeError: undefined is not a constructor (evaluating 'new ui_1.Property')

CONSOLE ERROR [native code]: ERROR TypeError: Could not load view for: RGridLayout.TypeError: undefined is not a constructor (evaluating 'new ui_1.Property')
2021-03-05 22:53:43.539732+0530 mzyoontailor[12214:886448] CONSOLE ERROR [native code]: ERROR CONTEXT {
  "view": {
    "def": {
      "nodeFlags": 33734657,
      "rootNodeFlags": 33554433,
      "nodeMatchedQueries": 0,
      "flags": 0,
      "nodes": [
        {
          "nodeIndex": 0,
          "parent": null,
          "renderParent": null,
          "bindingIndex": 0,
          "outputIndex": 0,
          "checkIndex": 0,
          "flags": 33554433,
          "childFlags": 180225,
          "directChildFlags": 49153,
          "childMatchedQueries": 0,
          "matchedQueries": {},
          "matchedQueryIds": 0,
          "references": {},
          "ngContentIndex": null,
          "childCount": 7,
          "bindings": [],
          "bindingFlags": 0,
          "outputs": [],
          "element": {
            "ns": "",
            "name": "ActionBar",
            "attrs": [
              [
                "",
                "class",
                "header"
              ]
            ],
            "template": null,
            "componentProvider":
CONSOLE ERROR [native code]: ERROR CONTEXT {
  "view": {
    "def": {
      "nodeFlags": 33734657,
      "rootNodeFlags": 33554433,
      "nodeMatchedQueries": 0,
      "flags": 0,
      "nodes": [
        {
          "nodeIndex": 0,
          "parent": null,
          "renderParent": null,
          "bindingIndex": 0,
          "outputIndex": 0,
          "checkIndex": 0,
          "flags": 33554433,
          "childFlags": 180225,
          "directChildFlags": 49153,
          "childMatchedQueries": 0,
          "matchedQueries": {},
          "matchedQueryIds": 0,
          "references": {},
          "ngContentIndex": null,
          "childCount": 7,
          "bindings": [],
          "bindingFlags": 0,
          "outputs": [],
          "element": {
            "ns": "",
            "name": "ActionBar",
            "attrs": [
              [
                "",
                "class",
                "header"
              ]
            ],

**Comment by xlmnxp** [comment]
use
```
tns plugin add @nativescript-rtl/ui@0.1.7
``` 
for NativeScript 6 and lower
