### ISSUE TITLE
Could you publish the new fix about "IOS pixelate when wrapped by any RTL Layout" to npm?

### ISSUE THREAD

**Issue by howieluo** [nativescript-rtl/ui#20]
The version 0.1.8 doesn't include the new fix. Could you please publish it? Thanks.

**Comment by howieluo** [comment]
Our project depends heavily on it.
Do you have any plan to update your published package version number on npm? 
Thanks a lot.

**Comment by xlmnxp** [comment]
> Our project depends heavily on it.
> Do you have any plan to update your published package version number on npm?
> Thanks a lot.

I will release it today 😄

**Comment by xlmnxp** [comment]
`📦  @nativescript-rtl/ui@0.1.9` published 😄
