### ISSUE TITLE
0.2.1 not packaged correctly on npm

### ISSUE THREAD

**Issue by edusperoni** [nativescript-rtl/ui#27]
It seems version 0.2.1 wasn't packaged correctly on npm, so it's missing a lot of files:

![image](https://user-images.githubusercontent.com/4061767/137731037-b2df50e5-065e-4271-a9d6-0ea80a73cad3.png)

**Comment by xlmnxp** [comment]
there issue because of `nsconfig.ts` file
I will fix it and I will make a release

**Comment by xlmnxp** [comment]
![image](https://user-images.githubusercontent.com/20779154/137834442-ab27bd88-257d-4588-a1fd-b6fbe97df97f.png)
