### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Carli0s** [nativescript-rtl/ui#3]
I'm trying to use this library, but it's not working.

I installed the library and copied the XML.

And to test i added isRtl="true" and also the style ="direction: rtl", also change this values  to view if it change.
 
​But this never change, always shows in ltr.

Please can you help me or say anything for i can continue ? thanks

**Comment by xlmnxp** [comment]
can you share your code here?

**Comment by Carli0s** [comment]
Hi ,

Thanks for reply, i looked the other issues and one was a solution for me. I am using angular, and i can look that i need to " register element" for this works

thanks, now is working
