### ISSUE TITLE
Make all layouts RTL from code

### ISSUE THREAD

**Issue by Izrab** [nativescript-rtl/ui#5]
When user changes app language from English to Arabic, this plugin should have a function to change all the layouts to RTL from code.

**Comment by xlmnxp** [comment]
@lzrab you can change language by `isRtl` property

**Comment by abozanona** [comment]
@xlmnxp Could you please explain your answer? Is the `isRtl` property supported for all elements? Could you provide a code snippet of how to use the `isRtl` property?

**Comment by xlmnxp** [comment]
@abozanona isRtl property work only in supported `Rtl` layouts
Example
```<rtl:WrapLayout orientation="horizontal" isRtl="false" width="210" height="210" backgroundColor="lightgray">
    <Label text="Label 1" width="70" height="70" backgroundColor="red"/>
    <Label text="Label 2" width="70" height="70" backgroundColor="green"/>
    <Label text="Label 3" width="70" height="70" backgroundColor="blue"/>
    <Label text="Label 4" width="70" height="70" backgroundColor="yellow"/>
  </rtl:WrapLayout>```
