### ISSUE TITLE
System.err: TypeError: Cannot read property 'setRotationY' of undefined

### ISSUE THREAD

**Issue by campions** [nativescript-rtl/ui#9]
The issue with setRotation is happening also on android

**Comment by xlmnxp** [comment]
@campions can you share full error message?

**Comment by campions** [comment]
> @campions can you share full error message?

`System.err: TypeError: Cannot read property 'setRotationY' of undefined

System.err: 

System.err: StackTrace:

System.err: 	Frame: function:'', file:'file:///node_modules\@nativescript-rtl\ui\stack-layout\stack-layout.android.js:50:42

System.err: 	Frame: function:'invoke', file:'file:///node_modules\@nativescript\core\timer\timer.js:20:47

System.err: 	Frame: function:'run', file:'file:///node_modules\@nativescript\core\timer\timer.js:24:12

System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)

System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)

System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)

System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)

System.err: 	at android.os.Handler.handleCallback(Handler.java:883)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)

System.err: 	at android.os.Looper.loop(Looper.java:214)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by xlmnxp** [comment]
> > @campions can you share full error message?
> 
> ```
> 
> System.err: 
> 
> System.err: StackTrace:
> 
> System.err: 	Frame: function:'', file:'file:///node_modules\@nativescript-rtl\ui\stack-layout\stack-layout.android.js:50:42
> 
> System.err: 	Frame: function:'invoke', file:'file:///node_modules\@nativescript\core\timer\timer.js:20:47
> 
> System.err: 	Frame: function:'run', file:'file:///node_modules\@nativescript\core\timer\timer.js:24:12
> 
> System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
> 
> System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
> 
> System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
> 
> System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1109)
> 
> System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1089)
> 
> System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1081)
> 
> System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
> 
> System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
> 
> System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 
> System.err: 	at android.os.Looper.loop(Looper.java:214)
> 
> System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> 
> System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> 
> System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 
> System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```
> ```

your code?

**Comment by campions** [comment]
in component
` <RStackLayout class="text-field">
          <TextField
            v-model="companySearchField"
            :hint="'orders.order.billing.billTo.company_name' | L"
          />
        </RStackLayout>`

and in the main.js
`
Vue.registerElement(
    "RGridLayout",
    () => require("@nativescript-rtl/ui").GridLayout
);

Vue.registerElement(
    "RWrapLayout",
    () => require("@nativescript-rtl/ui").WrapLayout
);

Vue.registerElement(
    "RAbsoluteLayout",
    () => require("@nativescript-rtl/ui").AbsoluteLayout
);

Vue.registerElement(
    "RDockLayout",
    () => require("@nativescript-rtl/ui").DockLayout
);

Vue.registerElement(
    "RStackLayout",
    () => require("@nativescript-rtl/ui").StackLayout
);
`

**Comment by xlmnxp** [comment]
@campions i will fix it soon

**Comment by campions** [comment]
> @campions i will fix it soon

thank you very much

**Comment by campions** [comment]
What is the status of this bug?

**Comment by xlmnxp** [comment]
@campions I can't get the issue in my device or emulator
can you share detail about your OS and device model?

**Comment by campions** [comment]
![image](https://user-images.githubusercontent.com/11190230/83107375-d5410b80-a0c6-11ea-8b63-351e05de8cc8.png)
this is my emulator details

**Comment by xlmnxp** [comment]
![test-rtl-min](https://user-images.githubusercontent.com/20779154/83360947-bde77400-a38d-11ea-86cc-e67432dd69b0.gif)
I can't get the message
I will make Vue project maybe the issue in it only

**Comment by xlmnxp** [comment]
closed because it inactive
